# Site settings
name: Echizen Ryoma
email: 790545771@qq.com
author: Echizen Ryoma
url: https://bigmousefive.github.io/
resume_site: https://bigmousefive.github.io/
github: https://github.com/BigMouseFive
baseurl: "/"
description: You still have lots more to work on!
meta_description: 戴锐;个人博客;
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: BigMouseFive

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

