# Site settings
title: Lemon - Blogs of Echizen
description: "Blogs of Echizen"
baseurl: "/" # for test: remove string '/space-jekyll-template' to ''
url: "https://bigmousefive.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Echzien Ryoma
user_title: Echzien Ryoma
email: 790545771@qq.com
wechat_username: five
github_username:  BigMouseFive
qq_username:  帒&龍馬
zhihu_url: 龙马 # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
gplus_username: 790545771ey@gmail.com
profile_picture: /assets/img/my_girl.png

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  hard_wrap: false
  syntax_highlighter: rouge
  transliterated_header_ids: true
  footnote_backlink: "&#8617;&#xfe0e;"
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: 主页
      url: /
      key_trigger: 1
    - title: 时间
      url: /posts
      key_trigger: 2
    - title: 分类
      url: /series
      key_trigger: 3
    - title: 标签
      url: /tags
      key_trigger: 4
    - title: 关于
      url: /about
      key_trigger: 5

# projects in header index
projects:
  - name: lemon01
    url: https://github.com/BigMouseFive/lemon01
  - name: lemon02
    url: https://github.com/BigMouseFive/lemon02

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'yulib.resource']
